export enum DIToken {
	CATEGORY_REPOSITORY_INTERFACE = 'CategoryRepositoryInterface',
	CATEGORY_SERVICE_INTERFACE = 'CategoryServiceInterface',
	USER_ACCOUNT_REPOSITORY_INTERFACE = 'UserAccountRepositoryInterface',
	USER_ACCOUNT_SERVICE_INTERFACE = 'UserAccountServiceInterface',
	AUTH_REPOSITORY_INTERFACE = 'AuthRepositoryInterface',
	AUTH_SERVICE_INTERFACE = 'AuthServiceInterface',
	USER_SESSION_REPOSITORY_INTERFACE = 'UserSessionRepositoryInterface',
	USER_SESSION_SERVICE_INTERFACE = 'UserSessionServiceInterface',
	USER_ROLE_REPOSITORY_INTERFACE = 'UserRoleRepositoryInterface',
	USER_ROLE_SERVICE_INTERFACE = 'UserRoleServiceInterface',
	ROLE_REPOSITORY_INTERFACE = 'RoleRepositoryInterface',
	ROLE_SERVICE_INTERFACE = 'RoleServiceInterface',
	ROLE_FEATURE_REPOSITORY_INTERFACE = 'RoleFeatureRepositoryInterface',
	ROLE_FEATURE_SERVICE_INTERFACE = 'RoleFeatureServiceInterface',
	FEATURE_REPOSITORY_INTERFACE = 'FeatureRepositoryInterface',
	FEATURE_SERVICE_INTERFACE = 'FeatureServiceInterface',
	FEATURE_GROUP_REPOSITORY_INTERFACE = 'FeatureGroupRepositoryInterface',
	FEATURE_GROUP_SERVICE_INTERFACE = 'FeatureGroupServiceInterface'
}
