import { Entity, Column } from 'typeorm';

/**
 * An entity class for item_category table in the database.
 */
@Entity('item_category')
export class CategoryEntity {
	/**
	 * PK of the table.
	 */
	@Column({
		name: 'item_category_id',
		type: 'int',
		comment: 'PK of the table.',
		generated: 'increment',
		primary: true,
		nullable: false,
		unique: true
	})
	categoryId: number;

	/**
	 * Unique code of the item category.
	 */
	@Column({
		name: 'code',
		type: 'varchar',
		length: 50,
		comment: 'Unique code of the item category.',
		nullable: false,
		unique: true
	})
	code: string;

	/**
	 * Name of the item category.
	 */
	@Column({
		name: 'item_category_name',
		type: 'varchar',
		length: 100,
		comment: 'Name of the item category.',
		nullable: false
	})
	categoryName: string;

	/**
	 * Remarks / description of the item category.
	 */
	@Column({
		name: 'remarks',
		type: 'varchar',
		length: 8000,
		comment: 'Name of the item category.',
		nullable: true
	})
	remarks: string;

	/**
	 * User id of a user who created the record.
	 */
	@Column({
		name: 'createdby',
		type: 'int',
		comment: 'User id of a user who created the record.',
		nullable: false
	})
	createdBy: number;

	/**
	 * Date and time when the record is created.
	 */
	@Column({
		name: 'createddate',
		type: 'datetime',
		comment: 'Date and time when the record is created.',
		nullable: false
	})
	createdDate: Date;

	/**
	 * User id of a user who modified the record.
	 */
	@Column({
		name: 'modifiedby',
		type: 'int',
		comment: 'User id of a user who modified the record.',
		nullable: true
	})
	modifiedBy: number;

	/**
	 * Date and time when the record is modified.
	 */
	@Column({
		name: 'modifieddate',
		type: 'datetime',
		comment: 'Date and time when the record is modified.',
		nullable: true
	})
	modifiedDate: Date;

	/**
	 * Is generated by the system.
	 */
	@Column({
		name: 'issystem',
		type: 'boolean',
		comment: 'Is generated by the system.',
		nullable: false
	})
	isSystem: boolean;
}
