import { Field, Int, ObjectType } from '@nestjs/graphql';
import { UserAccountEntity } from '../../user-account/entities/user-account.entity';
import { Entity, Column, ManyToMany, JoinTable } from 'typeorm';

/**
 * An entity class for item_category table in the database.
 */
@Entity('role')
@ObjectType('Role', { description: 'A master table to save all the roles in the system.' })
export class RoleEntity {
	/**
	 * PK of the table.
	 */
	@Column({
		name: 'role_id',
		type: 'smallint',
		comment: 'PK of the table.',
		generated: 'increment',
		primary: true,
		nullable: false,
		unique: true
	})
	@Field(type => Int, { description: 'PK of the table.' })
	roleId: number;

	/**
	 * Name of the role.
	 */
	@Column({
		name: 'role_name',
		type: 'varchar',
		length: 50,
		comment: 'Name of the role.',
		nullable: false
	})
	@Field({ nullable: false, description: 'Name of the role.' })
	roleName: string;

	/**
	 * User id of a user who created the record.
	 */
	@Column({
		name: 'createdby',
		type: 'int',
		comment: 'User id of a user who created the record.',
		nullable: false
	})
	@Field(type => Int, { nullable: false, description: 'User id of a user who created the record.' })
	createdBy: number;

	/**
	 * Date and time when the record is created.
	 */
	@Column({
		name: 'createddate',
		type: 'datetime',
		comment: 'Date and time when the record is created.',
		nullable: false
	})
	@Field({ nullable: false, description: 'Date and time when the record is created.' })
	createdDate: Date;

	/**
	 * User id of a user who modified the record.
	 */
	@Column({
		name: 'modifiedby',
		type: 'int',
		comment: 'User id of a user who modified the record.',
		nullable: true
	})
	@Field(type => Int, { nullable: true, description: 'User id of a user who modified the record.' })
	modifiedBy: number;

	/**
	 * Date and time when the record is modified.
	 */
	@Column({
		name: 'modifieddate',
		type: 'datetime',
		comment: 'Date and time when the record is modified.',
		nullable: true
	})
	@Field({ nullable: true, description: 'Date and time when the record is modified.' })
	modifiedDate: Date;

	/**
	 * Is generated by the system.
	 */
	@Column({
		name: 'issystem',
		type: 'boolean',
		comment: 'Is generated by the system.',
		nullable: false
	})
	@Field({ nullable: false, description: 'Is generated by the system.' })
	isSystem: boolean;

	/**
	 * Is default.
	 */
	@Column({
		name: 'isDefault',
		type: 'boolean',
		comment: 'Is default role or not.',
		nullable: true,
		default: false
	})
	@Field({ nullable: true, description: 'Is default role or not.', defaultValue: false })
	isDefault: boolean;

	@ManyToMany(() => UserAccountEntity, user => user.roles)
	@JoinTable({
		name: 'user_role',
		joinColumn: {
			name: 'role_id',
			referencedColumnName: 'roleId'
		},
		inverseJoinColumn: {
			name: 'user_id',
			referencedColumnName: 'userId'
		}
	})
	users: UserAccountEntity[];
}
