import { Transform, TransformFnParams } from 'class-transformer';
import {
	IsDefined,
	IsInt,
	Length,
	IsPositive,
	IsDateString,
	IsNotEmpty,
	IsBoolean,
	IsOptional
} from 'class-validator';

/**
 * A DTO class for Role.
 */
export class CreateRoleDto {
	/**
	 * Name of the role.
	 */
	@IsDefined()
	@IsNotEmpty()
	@Length(2, 100)
	@Transform(({ value }: TransformFnParams) => value.trim())
	roleName: string;

	/**
	 * User id of a user who created the record.
	 */
	@IsOptional()
	@IsInt()
	@IsPositive()
	createdBy: number;

	/**
	 * Date and time when the record is created.
	 */
	@IsOptional()
	@IsDateString()
	createdDate: string = new Date().toISOString();

	/**
	 * Is generated by the system.
	 */
	@IsDefined()
	@IsBoolean()
	isSystem: boolean;

	/**
	 * Is default.
	 */
	@IsOptional()
	@IsBoolean()
	isDefault?: boolean = false;
}
